[build-system]
requires      = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "MIR"
version = "0.0.1"
authors = [
    { name = "darkshapes", email = "91800957+exdysa@users.noreply.github.com" },
]
requires-python = ">= 3.11"
license = { file = "LICENSE" }
description = "Machine Intelligence Resource URI Schema Codebase"
readme = "README.md"

dependencies = [
    "nnll @ git+https://github.com/darkshapes/nnll@main",
    "pydantic>=2.11.5",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev      = ["pytest>=8.3.5", "pytest-asyncio>=1.0.0", "ruff>=0.11.12","mir[lmstudio,ollama,openai]"]
lmstudio = ["lmstudio>=1.3.1"]
ollama   = ["ollama>=0.5.1"]
openai   = ["openai>=1.84.0"]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.5",
    "pytest-asyncio>=1.0.0",
    "ruff>=0.11.12",
    "mir[lmstudio,ollama,openai]"
]
lmstudio = ["lmstudio>=1.3.1"]
ollama   = ["ollama>=0.5.1"]
openai   = ["openai>=1.84.0"]

[project.scripts]
mir-maid  = "mir.mir_maid:main"
mir-find  = "mir.compare_layers:main"
mir-hash  = "mir.hash256:main"
mir-add   = "mir.mir:main"
mir-parse = "mir.read_state_dict:main"

[project.urls]
Homepage = "https://github.com/darkshapes/MIR"

[tool.setuptools]
packages = ["mir"]

[tool.setuptools.package-data]
'mir' = ['config/*.json']

[tool.ruff]
line-length    = 140
include        = ["*.py"]
extend-exclude = ["^tests/.*$", "test.*$"]

# [tool.ruff.format]
# exclude = ["*.py"]

[tool.pylint]
max-line-length = 140
ignore-paths    = ["^tests/.*$", "test_.*$"]
disable         = ["C0415", "E731"]

[tool.ruff.lint.pycodestyle]
max-line-length               = 140
ignore-overlong-task-comments = true

[tool.typos]
files.extend-exclude = ["^tests/.*$", "test.*$"]
default.extend-words = { "ot" = "ot" }

[tool.uv.sources]
nnll = { git = "https://github.com/darkshapes/nnll", rev = "main" }
