[build-system]
requires      = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "MIR"
version = "0.0.1"
description = "Machine Intelligence Resource URI Schema"
readme = "README.md"
dependencies = [
    "huggingface-hub[hf-transfer,hf-xet]>=0.32.3",
    "lmstudio>=1.3.1",
    "nnll",
    "ollama>=0.5.1",
    "openai>=1.82.1",
    "pydantic>=2.11.5",
    "tqdm>=4.67.1",
    "nnll @ git+https://github.com/darkshapes/nnll@main",
]

[project.scripts]
mir-maid  = "mir.mir_maid:main"
mir-find  = "mir.compare_layers:main"
mir-hash  = "mir.hash256:main"
mir-add   = "mir.mir:main"
mir-parse = "nnll_36:main"

[project.urls]
Homepage = "https://github.com/darkshapes/MIR"

[tool.setuptools]
packages = ["mir"]

[tool.setuptools.package-data]
'mir' = ['config/*.json']


[tool.ruff]
line-length    = 140
include        = ["*.py"]
extend-exclude = ["^tests/.*$", "test.*$"]

# [tool.ruff.format]
# exclude = ["*.py"]

[tool.pylint]
max-line-length = 140
ignore-paths    = ["^tests/.*$", "test_.*$"]
disable         = ["C0415"]

[tool.ruff.lint.pycodestyle]
max-line-length               = 140
ignore-overlong-task-comments = true

[tool.typos]
files.extend-exclude = ["^tests/.*$", "test.*$"]
default.extend-words = { "ot" = "ot" }

[tool.uv.sources]
nnll = { git = "https://github.com/darkshapes/nnll", rev = "main" }
