[build-system]
requires      = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
authors = [
    { name = "darkshapes", email = "91800957+exdysa@users.noreply.github.com" },
]
description = "Machine Intelligence Resource URI Schema Codebase"
license = { file = "LICENSE" }
name = "MIR"
readme = "README.md"
requires-python = ">= 3.11"
version = "0.0.1"
keywords = ["ML", "AI", "URI", "schema", "diffusion", "LLM", "identification"]
classifiers = [
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

dependencies = ["nnll @ /Users/unauthorized/Documents/GitHub/darkshapes/nnll"]

[dependency-groups]
dev      = ["pytest>=8.3.5", "pytest-asyncio>=1.0.0", "ruff>=0.11.12", "mir[full]"]
lmstudio = ["lmstudio>=1.3.1"]
ollama   = ["ollama>=0.5.1"]
openai   = ["openai>=1.84.0"]
full     = ["mir[lmstudio,ollama,openai]"]
# vllm     = ["vllm>=0.9.0.1"]

[project.optional-dependencies]
dev      = ["pytest>=8.3.5", "pytest-asyncio>=1.0.0", "ruff>=0.11.12", "mir[full]"]
lmstudio = ["lmstudio>=1.3.1"]
ollama   = ["ollama>=0.5.1"]
openai   = ["openai>=1.84.0"]
# vllm     = ["vllm>=0.9.0.1"]
full = ["mir[lmstudio,ollama,openai]"]

[project.urls]
Homepage      = "https://github.com/darkshapes/MIR"
Documentation = "https://github.com/darkshapes/sdbx/wiki"

[project.scripts]
mir-maid  = "mir.mir_maid:main"
mir-find  = "mir.compare_layers:main"
mir-hash  = "mir.hash256:main"
mir-add   = "mir.mir:main"
mir-parse = "mir.read_state_dict:main"

[tool.setuptools]
packages = ["mir"]

[tool.setuptools.package-data]
'mir' = ['config/*.json']

[tool.ruff]
line-length    = 140
include        = ["*.py"]
extend-exclude = ["^tests/.*$", "test.*$"]

# [tool.ruff.format]
# exclude = ["*.py"]

[tool.pylint]
max-line-length = 140
ignore-paths    = ["^tests/.*$", "test_.*$"]
disable         = ["C0415"]

[tool.ruff.lint.pycodestyle]
max-line-length               = 140
ignore-overlong-task-comments = true

[tool.typos]
files.extend-exclude = ["^tests/.*$", "test.*$"]
default.extend-words = { "ot" = "ot" }

[tool.uv.sources]
nnll = { git = "https://github.com/darkshapes/nnll", rev = "main" }
