name: Pull and Commit JSON File

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies and build
        run: |
          sudo apt-get update
          sudo apt-get -y install libportaudio2
          pip cache purge
          rm -rf venv
          python -m venv .venv
          source .venv/bin/activate
          python3 -m pip install --upgrade pip
          pip install "."
          cd mir
          mir